# author: z217
# date: 2021/01/06
spring:
  application:
    name: duo-duo-pin-demo
  datasource:
    url: jdbc:mysql://*.*.*.*:*/DuoDuoPin?serverTimezone=CTT&useSSL=false&tcpKeepAlive=true&allowPublicKeyRetrieval=true
    username: ***
    password: ******
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 15
      #      连接生命时长
      max-lifetime: 1200000
      connection-test-query: SELECT 1
      #      连接idle状态最大时长
      idle-timeout: 600000
      #      等待连接池分配时长
      connection-timeout: 30000
    tomcat:
      validation-query: SELECT 1
      test-on-borrow: true
      #      打印超时连接错误
      log-abandoned: true
      #      移除超时连接
      remove-abandoned: true
      remove-abandoned-timeout: 300
      #      每5分钟检测空闲10分钟的连接
      min-evictable-idle-time-millis: 600000
      time-between-eviction-runs-millis: 300000
      test-while-idle: true
  redis:
    host: *.*.*.*
    port: ****
    password: ******
    timeout: 60s
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    open-in-view: false

server:
  port: 8080

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    root: warn